In [1]:
# Computerphile (https://www.youtube.com/watch?v=G_UYXzGuqvM)

In [2]:
board = [
        [3, 9, 0, 0, 5, 0, 0, 0, 0],
        [0, 0, 0, 2, 0, 0, 0, 0, 5],
        [0, 0, 0, 7, 1, 9, 0, 8, 0],

        [0, 5, 0, 0, 6, 8, 0, 0, 0],
        [2, 0, 6, 0, 0, 3, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 4],

        [5, 0, 0, 0, 0, 0, 0, 0, 0],
        [6, 7, 0, 1, 0, 5, 0, 4, 0],
        [1, 0, 9, 0, 0, 0, 2, 0, 0]
    ]

In [3]:
import numpy as np

In [9]:
print(np.matrix(board))

[[3 9 0 0 5 0 0 0 0]
 [0 0 0 2 0 0 0 0 5]
 [0 0 0 7 1 9 0 8 0]
 [0 5 0 0 6 8 0 0 0]
 [2 0 6 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 0 4]
 [5 0 0 0 0 0 0 0 0]
 [6 7 0 1 0 5 0 4 0]
 [1 0 9 0 0 0 2 0 0]]


In [5]:
def possible(y,x,n):
    global board
    for i in range(0,9):
        if board[y][i] == n:
            return False
    for i in range(0,9):
        if board[i][x] == n:
            return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if board[y0+i][x0+j] == n:
                return False
    return True

In [6]:
possible(4,4,3)
# (col, row, desired number)

False

In [7]:
def solve():
    global board
    for y in range(9):
        for x in range(9):
            if board[y][x] == 0:
                for n in range(1,10):
                    if possible(y,x,n):
                        board[y][x] = n
                        solve()
                        board[y][x] = 0
                return  # if not solved, not possible to solve
    print(np.matrix(board))
    input("More?") # other possible answer 

In [8]:
solve()

[[3 9 1 8 5 6 4 2 7]
 [8 6 7 2 3 4 9 1 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 7 1]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]


More? yes


[[3 9 7 8 5 6 4 2 1]
 [8 6 1 2 3 4 9 7 5]
 [4 2 5 7 1 9 6 8 3]
 [7 5 4 9 6 8 1 3 2]
 [2 1 6 4 7 3 5 9 8]
 [9 3 8 5 2 1 7 6 4]
 [5 4 3 6 9 2 8 1 7]
 [6 7 2 1 8 5 3 4 9]
 [1 8 9 3 4 7 2 5 6]]


More? yes
